In [9]:
#program to create am array and perform addition of teo matrices.(using list and numpy array)
#method 1: using list
matrix1=([[1,2,3],[4,5,6],[7,8,9]])
matrix2=([[8,9,7],[6,5,4],[3,2,1]])
result=([[0,0,0],[0,0,0],[0,0,0]])

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j]=matrix1[i][j]+matrix2[i][j]
print("matrix 1:")
for row in matrix1:
    print(row)
print("\nmatrix 2:")
for row in matrix2:
    print(row)
print("\nSum of matrix 1 and matrix 2:")
for row in result:
    print(row)

matrix 1:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

matrix 2:
[8, 9, 7]
[6, 5, 4]
[3, 2, 1]

Sum of matrix 1 and matrix 2:
[9, 11, 10]
[10, 10, 10]
[10, 10, 10]


In [6]:
import numpy as np
## create 2 matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
## add the two matrices
C=A+B
print("matrix A is:")
print(A)
print("matrix B is:")
print(B)
print("Addition of the matrices is:")
print(C)



matrix A is:
[[1 2]
 [3 4]]
matrix B is:
[[5 6]
 [7 8]]
Addition of the matrices is:
[[ 6  8]
 [10 12]]
